# Generated by Django 3.2.8 on 2026-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=models.TextField(blank=True, null=True, verbose_name="Vector d'embedding (JSON)"),
        ),
        migrations.AddField(
            model_name='event',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Model d'embedding"),
        ),
        migrations.AddField(
            model_name='event',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualització embedding'),
        ),
    ]
