# Generated by Django 3.2.8 on 2026-01-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Missatge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Data d'enviament")),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminat')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Destacat')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.event', verbose_name='Esdeveniment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuari')),
            ],
            options={
                'verbose_name': 'Missatge de Xat',
                'verbose_name_plural': 'Missatges de Xat',
                'ordering': ['created_at'],
            },
        ),
    ]
